[package]
name = "upnp-mapping"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
igd-next.workspace = true
log.workspace = true
tokio = { workspace = true, features = ["net", "rt", "sync", "time", "macros"] }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
