import "./globals.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Copyright from "@/components/Copyright";
import Logo from "@/components/Logo";
import MenuButton from "@/components/MenuButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="h-20 flex items-center justify-between sticky px-12">
          <Logo />
          <MenuButton />
        </header>
        <nav>TODO</nav>
        <main>{children}</main>
        <footer className="row-start-3 flex gap-[24px] flex-wrap items-center justify-center">
          <Copyright />
        </footer>
      </body>
    </html>
  );
}
