import "./globals.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Copyright from "@/components/Copyright";
import Logo from "@/components/Logo";
import MenuButton from "@/components/MenuButton";
import NavItem from "@/components/NavItem";
import { NAV_LIST } from "@/constants/nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="h-screen flex flex-col px-12">
          <header className="h-20 flex items-center justify-between sticky">
            <Logo />
            <MenuButton />
          </header>
          <nav className="flex flex-wrap *:flex-[1_1_33.3%]">
            {NAV_LIST.map((item) => (
              <NavItem key={item.href} href={item.href}>
                {item.title}
              </NavItem>
            ))}
          </nav>
          <main className="flex-[1_1_1px]">{children}</main>
          <footer className="h-15 flex gap-[24px] flex-wrap items-center ">
            <Copyright />
          </footer>
        </div>
      </body>
    </html>
  );
}
